name: "Pollen"
description: "The Pollen Programming Language"

url: "http://amaret.com"

baseurl: "/pollen"

# Exclude directories from the conversion
include: ['./static']

# Dependencies
markdown:         rdiscount
highlighter:      pygments

# Use pygments to highlight code blocks
pygments:     true

# Permalinks
permalink:        pretty

# Server
source:           ./
destination:      ./_site

# Custom vars
#current_version:  0.2.86
